Feature/add gracefully error handling BOUBEST443
mimir-org/tyle pull request #820
Opened 2023-10-13 07:54 UTC by AndyEPandy

Added 207 response if any "minror" errors occurs during update or creating Terminal, Block, Attributes etc in backend.

2023-10-13 11:37 UTC, jorgen-norheim requested changes
Mye bra, litt småpirk her og der, og så vil jeg gjerne at du bruker metoden jeg linker til i kontrollerne. 🙂 

Ellers: husk BOUBEST-XXX i branchnavn fremover. 🎗️

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Api/Attributes/AttributeGroupsController.cs
> +            return StatusCode(422, ex.Message);
Her finnes det en innebygd metode vi kan bruke: [UnprocessableEntity](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.unprocessableentity?view=aspnetcore-7.0#microsoft-aspnetcore-mvc-controllerbase-unprocessableentity(system-object))

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Api/Blocks/BlocksController.cs
> +using System;
Denne tror jeg ikke er nødvending.

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Api/Blocks/BlocksController.cs
> +using Tyle.Api.Attributes;
Ikke denne heller.

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Api/Properties/launchSettings.json
> +      "applicationUrl": "http://localhost:5001",
Du trenger ikke endre denne, launch heller "TypeLibrary" fra nedtrekkslista.

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Api/Terminals/TerminalsController.cs
> +using Tyle.Api.Blocks;
Denne tror jeg ikke er nødvendig.

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Application/Attributes/IAttributeGroupRepository.cs
> +using Tyle.Core.Common;
Trengs ikke lengre.

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Application/Common/ITypeRepository.cs
> +using Tyle.Core.Common;
Trengs ikke lengre.

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Attributes/AttributeGroupRepository.cs
> +
Fjerne disse?

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Attributes/AttributeGroupRepository.cs
> +                throw new KeyNotFoundException($"Could not find and add {attributeId} to the attribute group. Please ensure that the attribute you add exists.");
Bedre å skrive "...find and add the attribute with id"?
Siste setning foreslår jeg at du skriver "attributes".

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Attributes/AttributeGroupRepository.cs
> +                throw new KeyNotFoundException($"Something happened during updating the attribute group {request.Name}. Could not find one or more of the attributes.");
Bør gjerne ha med id her også, kan sikkert bruke samme formulering som over.

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Attributes/AttributeRepository.cs
> +        var response = new AttributeType
Endre navn tilbake til attribute?

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Attributes/AttributeRepository.cs
> +                throw new KeyNotFoundException($"could not remove attribute with id {unitId}. Please ensure the attribute to remove is correct and try again later.");
Blir feil å si remove her.

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Attributes/AttributeRepository.cs
> +            throw new KeyNotFoundException($"Could not add predicate with id {response.PredicateId}. Please check and try again later");
Litt mange varianter av feilmeldingen, tenker den bør se tilnærmet lik ut over alt.

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Attributes/AttributeRepository.cs
> +using Tyle.Core.Common;
Trengs denne?

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Blocks/BlockRepository.cs
> +using Tyle.Core.Common;
Sjekk om disse importene trengs.

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Terminals/TerminalRepository.cs
> +using Tyle.Core.Common;
Trengs disse importene?

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Terminals/TerminalRepository.cs
> +
Fjerne?

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Terminals/TerminalRepository.cs
> +
Fjerne?

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Terminals/TerminalRepository.cs
> +
Fjerne?

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Terminals/TerminalRepository.cs
> +
Fjerne?

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Terminals/TerminalRepository.cs
> +
Fjerne?

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Terminals/TerminalRepository.cs
> +        return await Get(id); ;
Her er det en ; for mye

2023-10-13 11:37 UTC, jorgen-norheim commented on src/server/Tyle.Api/CustomExeptionHandler.cs
Virker ikke som denne er i bruk, i så fall bør den slettes.

2023-10-13 13:45 UTC, AndyEPandy commented on src/server/Tyle.Api/Attributes/AttributeGroupsController.cs
> +    [ProducesResponseType(StatusCodes.Status422UnprocessableEntity)]
Gjort på alle

2023-10-13 13:45 UTC, AndyEPandy commented on src/server/Tyle.Api/Attributes/AttributeGroupsController.cs
> +            return StatusCode(422, ex.Message);
Gjort på alle

2023-10-13 13:46 UTC, AndyEPandy commented on src/server/Tyle.Api/Blocks/BlocksController.cs
> +using System;
Fjernet

2023-10-13 13:46 UTC, AndyEPandy commented on src/server/Tyle.Api/Blocks/BlocksController.cs
> +using Tyle.Api.Attributes;
Fjernet

2023-10-13 13:46 UTC, AndyEPandy commented on src/server/Tyle.Persistence/Terminals/TerminalRepository.cs
> +
Fjernet

2023-10-13 13:46 UTC, AndyEPandy commented on src/server/Tyle.Persistence/Terminals/TerminalRepository.cs
> +
Fjernet

2023-10-13 13:46 UTC, AndyEPandy commented on src/server/Tyle.Persistence/Terminals/TerminalRepository.cs
> +
Fjernet

2023-10-13 13:47 UTC, AndyEPandy commented on src/server/Tyle.Persistence/Terminals/TerminalRepository.cs
> +        return await Get(id); ;
Fjernet

2023-10-13 13:47 UTC, AndyEPandy commented on src/server/Tyle.Api/CustomExeptionHandler.cs
Fjernet

2023-10-13 13:47 UTC, AndyEPandy commented on src/server/Tyle.Api/Properties/launchSettings.json
> +      "applicationUrl": "http://localhost:5001",
Satt tilbake til 44598

2023-10-16 07:42 UTC, jorgen-norheim requested changes
Ser veldig fint ut! Noen skrivefeil som må fikses, og så er det noen unresolved fra forrige PR (et variabelnavn, og tomme linjer). Ser at du også har lagt til flere tomme linjer, kanskje se gjennom files changed og fikse det?

2023-10-16 07:42 UTC, jorgen-norheim commented on src/server/Tyle.Api/Attributes/AttributeGroupsController.cs
> +using Tyle.Core.Common;
Trengs denne?

2023-10-16 07:42 UTC, jorgen-norheim commented on src/server/Tyle.Api/Attributes/AttributesController.cs
> +using Tyle.Core.Common;
Og denne?

2023-10-16 07:42 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Common/ExeptionMessage.cs
Feil i navnet, det er Exception med c 🤓

2023-10-16 07:42 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Common/ExeptionMessage.cs
> +            sb.Append("Please check and try again later");
Hiv på et punktum her.

2023-10-16 07:42 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Common/ExeptionMessage.cs
> +            sb.Append($"Could not {action} {typeOfObject}");
Tror du må konvertere action til lower case her?

2023-10-16 08:52 UTC, jorgen-norheim requested changes
Fant litt mer smågodt 🍬

2023-10-16 08:52 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Attributes/AttributeRepository.cs
> +
Fint om du fjerner disse også 😸

2023-10-16 08:52 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Attributes/AttributeRepository.cs
> +                throw new KeyNotFoundException(ExceptionMessage.CreateExeptionMessage(ExceptionMessage.TypeOfMessage.Remove, "attribute", unitId.ToString()));
Mener det skal stå Add, ikke Remove her. Tror også det er "unit" du skal sende inn, ikke "attribute".

2023-10-16 08:52 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Terminals/TerminalRepository.cs
> +                throw new KeyNotFoundException(ExceptionMessage.CreateExeptionMessage(ExceptionMessage.TypeOfMessage.Add, "terminal classifier", classifierId.ToString()));
Her skal det vel stå classifier, ikke terminal classifier.

2023-10-16 08:52 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Terminals/TerminalRepository.cs
> +            throw new KeyNotFoundException(ExceptionMessage.CreateExeptionMessage(ExceptionMessage.TypeOfMessage.Add, "terminal purpose", request.PurposeId.ToString()));
Purpose, ikke terminal purpose.

2023-10-16 08:52 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Terminals/TerminalRepository.cs
> +            throw new KeyNotFoundException(ExceptionMessage.CreateExeptionMessage(ExceptionMessage.TypeOfMessage.Add, "medium purpose", request.MediumId.ToString()));
Medium, ikke medium purpose.

2023-10-16 08:52 UTC, jorgen-norheim commented on src/server/Tyle.Persistence/Common/ExceptionMessage.cs
> +        public static string CreateExeptionMessage(TypeOfMessage action, string typeOfObject, string? id = null)
Her mangler det fremdeles en c i Exception

2023-10-16 09:59 UTC, jorgen-norheim approved these changes
💯

2023-10-16 10:09 UTC, merged